name: CI - Python (PyPA Sample)

on:
  workflow_dispatch:

jobs:
  python-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'   

      - name: Upgrade pip & install build/test tooling
        run: |
          python -m pip install --upgrade pip
          # 'build' creates sdist and wheel from pyproject.toml (PEP 517)
          pip install build
          # install test runner if you plan to add/keep tests
          pip install pytest

      
      - name: Build package (sdist & wheel)
        run: |
          python -m build
          mkdir -p staging
          cp dist/* staging/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Package
          path: staging

         # ------------------ DOCKER LOGIN (Docker Hub) ------------------
      - name: docker log in
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

         # ------------------ DOCKER LOGIN (GHCR) ------------------
      - name: Docker login (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

         # ------------------ DOCKER LOGIN (AZURE) ------------------  
      - name: Docker login (Azure)
        uses: docker/login-action@v3
        with:
          registry: ccrazurebhuvana.azurecr.io
          username: ${{ vars.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}    
  
          # ------------------ IMAGE TAG METADATA ------------------
 
      - name: Get short commit SHA
        id: tag-vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT  
     

          # ------------------ BUILD & PUSH IMAGE (MULTI-REGISTRY) ------------------
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ${{ vars.DOCKER_USERNAME }}/python-project:latest
            ${{ vars.DOCKER_USERNAME }}/python-project:sha-${{ steps.tag-vars.outputs.short_sha }}

            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:sha-${{ steps.tag-vars.outputs.short_sha }}

            ${{ vars.AZURE_ACR_NAME }}.azurecr.io/python-project:latest
            ${{ vars.AZURE_ACR_NAME }}.azurecr.io/python-project:sha-${{ steps.tag-vars.outputs.short_sha }}